name: Production Private Deploy via AWS SSM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # မိမိ EC2 တည်ရှိသော AWS Region နာမည် ပြောင်းပါ (ဥပမာ- ap-southeast-1)

      - name: Deploy via AWS Systems Manager (SSM)
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "sudo apt update -y",
              "sudo apt install git nginx -y",
              "if [ -d \"aws-cicd-demo\" ]; then cd aws-cicd-demo && sudo git pull origin main; else sudo git clone https://github.com/pyaephyoe783/aws-cicd-demo.git; fi",
              "sudo cp -f /home/ubuntu/aws-cicd-demo/index.html /var/www/html/index.html || sudo cp -f aws-cicd-demo/index.html /var/www/html/index.html",
              "sudo systemctl restart nginx"
            ]'