name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt update -y
            sudo apt install git nginx -y
            
            if [ -d "aws-cicd-demo" ]; then
              cd aws-cicd-demo && sudo git pull origin main
            else
              sudo git clone https://github.com/pyaephyoe783/aws-cicd-demo.git
              cd aws-cicd-demo
            fi

            sudo cp -f index.html /var/www/html/index.html
            sudo systemctl restart nginx